using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Options;
using Npgsql;
using PersonalAgent.Configuration;

namespace PersonalAgent.Services;

internal class AgentMemorySchemaInitializer(IOptions<AgentMemoryOptions> options, ILogger<AgentMemorySchemaInitializer> logger) : IHostedService
{
    private readonly AgentMemoryOptions _options = options.Value;

    public async Task StartAsync(CancellationToken cancellationToken)
    {
        if (!_options.CreateInfrastructure) return;

        await using var connection = new NpgsqlConnection(_options.ConnectionString);
        await connection.OpenAsync(cancellationToken);

        if (_options.EnableSemanticMemory)
            await ExecuteNonQueryAsync(connection, "CREATE EXTENSION IF NOT EXISTS vector;", cancellationToken);

        await ExecuteNonQueryAsync(connection, BuildSchemaSql(), cancellationToken);
        logger.LogInformation("Ensured agent memory schema {Schema} exists", _options.Schema);
    }

    public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;

    private async Task ExecuteNonQueryAsync(NpgsqlConnection connection, string sql, CancellationToken cancellationToken)
    {
        await using var command = new NpgsqlCommand(sql, connection);
        await command.ExecuteNonQueryAsync(cancellationToken);
    }

    private string BuildSchemaSql()
    {
        var schema = QuoteIdentifier(_options.Schema);
        var sessionsTable = QualifiedTableName(_options.SessionsTableName);
        var transcriptMessagesTable = QualifiedTableName(_options.TranscriptMessagesTableName);
        var memoryRecordsTable = QualifiedTableName(_options.MemoryRecordsTableName);
        var vectorColumnDefinition = _options.EnableSemanticMemory
            ? $", embedding vector({_options.VectorDimensions}) NULL"
            : string.Empty;
        var vectorIndexSql = _options.EnableSemanticMemory
            ? $"CREATE INDEX IF NOT EXISTS {QuoteIdentifier($"ix_{_options.MemoryRecordsTableName}_embedding")} ON {memoryRecordsTable} USING hnsw (embedding vector_cosine_ops);"
            : string.Empty;
        var alterMemoryTableSql = _options.EnableSemanticMemory
            ? $"ALTER TABLE {memoryRecordsTable} ADD COLUMN IF NOT EXISTS embedding vector({_options.VectorDimensions}) NULL;"
            : string.Empty;

        return $"""
            CREATE SCHEMA IF NOT EXISTS {schema};

            CREATE TABLE IF NOT EXISTS {sessionsTable}
            (
                session_id uuid PRIMARY KEY,
                session_state jsonb NOT NULL,
                session_state_version integer NOT NULL,
                last_message_seq bigint NOT NULL DEFAULT 0,
                created_at timestamptz NOT NULL,
                updated_at timestamptz NOT NULL,
                last_message_at timestamptz NULL
            );

            CREATE INDEX IF NOT EXISTS {QuoteIdentifier($"ix_{_options.SessionsTableName}_updated_at")} ON {sessionsTable} (updated_at DESC);

            CREATE TABLE IF NOT EXISTS {transcriptMessagesTable}
            (
                message_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                session_id uuid NOT NULL REFERENCES {sessionsTable} (session_id) ON DELETE CASCADE,
                message_seq bigint NOT NULL,
                role text NOT NULL,
                content text NOT NULL,
                metadata jsonb NULL,
                created_at timestamptz NOT NULL,
                CONSTRAINT {QuoteIdentifier($"uq_{_options.TranscriptMessagesTableName}_session_seq")} UNIQUE (session_id, message_seq)
            );

            CREATE INDEX IF NOT EXISTS {QuoteIdentifier($"ix_{_options.TranscriptMessagesTableName}_session_created_at")} ON {transcriptMessagesTable} (session_id, created_at);

            CREATE TABLE IF NOT EXISTS {memoryRecordsTable}
            (
                memory_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                session_id uuid NULL REFERENCES {sessionsTable} (session_id) ON DELETE CASCADE,
                source_message_id bigint NULL REFERENCES {transcriptMessagesTable} (message_id) ON DELETE SET NULL,
                memory_kind text NOT NULL,
                content text NOT NULL,
                metadata jsonb NULL,
                embedding_model text NULL{vectorColumnDefinition},
                created_at timestamptz NOT NULL,
                updated_at timestamptz NOT NULL
            );

            {alterMemoryTableSql}
            CREATE INDEX IF NOT EXISTS {QuoteIdentifier($"ix_{_options.MemoryRecordsTableName}_session_created_at")} ON {memoryRecordsTable} (session_id, created_at DESC);
            {vectorIndexSql}
            """;
    }

    private string QualifiedTableName(string tableName) => $"{QuoteIdentifier(_options.Schema)}.{QuoteIdentifier(tableName)}";

    private static string QuoteIdentifier(string identifier) => new NpgsqlCommandBuilder().QuoteIdentifier(identifier);
}
