FROM mcr.microsoft.com/dotnet/sdk:11.0.100-rc.1@sha256:ab11199f8a0cded1d667111a0d4f0906567c3a17348a7181f9781d12cc5eb6f9
ENV DOTNET_CLI_HOME=/work DOTNET_CLI_TELEMETRY_OPTOUT=1 DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1 DOTNET_NOLOGO=1 DOTNET_EnableDiagnostics=0 NUGET_PACKAGES=/work/packages MSBUILDDISABLENODEREUSE=1
COPY automation-sandbox /template
RUN sed -i 's/\r$//' /template/run.sh
USER 65532:65532
WORKDIR /work
ENTRYPOINT ["timeout", "--signal=KILL", "95", "/bin/sh", "/template/run.sh"]
