<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>adba50a8-b9ab-4317-bb6d-4b928dbb4efd</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AgentPlayground.Contracts\AgentPlayground.Contracts.csproj" />
        <ProjectReference Include="..\AgentPlayground.Integrations\AgentPlayground.Integrations.csproj" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>PersonalAgent.Web.Tests</_Parameter1>
        </AssemblyAttribute>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>DynamicProxyGenAssembly2</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
        <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid" />
        <PackageReference Include="MudBlazor" />
        <PackageReference Include="Markdig" />
        <PackageReference Include="MassTransit" />
        <PackageReference Include="MassTransit.SqlTransport.PostgreSQL" />
    </ItemGroup>
</Project>
